### ISSUE TITLE
Error with 'executable_path'

### ISSUE THREAD

**Issue by SmiluxByte** [efenatuyo/snapchat-score#1]
**Hello, I tried to run the python file but encountered an error. Could you please help me with the problem? Greetings Marlon.**

$ python main.py
Traceback (most recent call last):
  File "C:\Users\stoff\snapchat-score\main.py", line 62, in <module>
    snapchat.farm_points()
  File "C:\Users\stoff\snapchat-score\main.py", line 26, in farm_points
    driver = self.driver()
             ^^^^^^^^^^^^^
  File "C:\Users\stoff\snapchat-score\main.py", line 21, in driver
    driver = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'executable_path'

**Comment by efenatuyo** [comment]
due to changes in selenium < 4.10.0 this option does not work anymore since it got removed
![image](https://github.com/efenatuyo/snapchat-score/assets/113731512/bec4d0f6-29f3-4c2d-aaba-feb21f0b6498)

https://stackoverflow.com/questions/76550506/typeerror-webdriver-init-got-an-unexpected-keyword-argument-executable-p

you can just downgrade selenium and it should work

**Comment by SmiluxByte** [comment]
Its working now. Its really fast and thats the problem my chrome tab shows "Out of Memory"
What can i do? and the website crashes

selenium.common.exceptions.WebDriverException: Message: **unknown error: session deleted because of page crash**
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=103.0.5060.53)h
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=103.0.5060.53)
Stacktrace:
Backtrace:
        Ordinal0 [0x00AD5FD3+2187219]
Stacktrace:
Backtrace:
        Ordinal0 [0x00AD5FD3+2187219]
        Ordinal0 [0x00A6E6D1+1763025]
        Ordinal0 [0x00983D40+802112]
        Ordinal0 [0x00975C11+744465]
        Ordinal0 [0x00974C28+740392]
        Ordinal0 [0x00975228+741928]
        Ordinal0 [0x0097F00F+782351]
        Ordinal0 [0x0098A308+828168]
        Ordinal0 [0x009DD1DF+1167839]
        Ordinal0 [0x009CC9A6+1100198]
        Ordinal0 [0x009A6F80+946048]
        Ordinal0 [0x009A7E76+949878]
        GetHandleVerifier [0x00D790C2+2721218]
        GetHandleVerifier [0x00D6AAF0+2662384]
        GetHandleVerifier [0x00B6137A+526458]
        GetHandleVerifier [0x00B60416+522518]
        Ordinal0 [0x00A74EAB+1789611]
        Ordinal0 [0x00A797A8+1808296]
        Ordinal0 [0x00A79895+1808533]
        Ordinal0 [0x00A826C1+1844929]
        BaseThreadInitThunk [0x7680FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77AD7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77AD7C3E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\stoff\snapchat-score\main.py", line 62, in <module>
    snapchat.farm_points()
  File "C:\Users\stoff\snapchat-score\main.py", line 57, in farm_points
    html_element = driver.find_element(By.TAG_NAME, "html")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stoff\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stoff\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\stoff\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
Backtrace:
        Ordinal0 [0x00AD5FD3+2187219]
        Ordinal0 [0x00A6E6D1+1763025]
        Ordinal0 [0x00983D40+802112]
        Ordinal0 [0x009A6A00+944640]
        Ordinal0 [0x009CCA80+1100416]
        Ordinal0 [0x009CA8D3+1091795]
        Ordinal0 [0x009CA489+1090697]
        Ordinal0 [0x00965447+676935]
        Ordinal0 [0x009659C3+678339]
        Ordinal0 [0x00965DFA+679418]
        GetHandleVerifier [0x00D790C2+2721218]
        GetHandleVerifier [0x00D6AAF0+2662384]
        GetHandleVerifier [0x00B6137A+526458]
        GetHandleVerifier [0x00B60416+522518]
        Ordinal0 [0x00A74EAB+1789611]
        Ordinal0 [0x009651D7+676311]
        Ordinal0 [0x00964C88+674952]
        GetHandleVerifier [0x00D9BEDC+2864092]
        BaseThreadInitThunk [0x7680FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77AD7C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77AD7C3E+238]


C:\Users\stoff\snapchat-score>

**Comment by efenatuyo** [comment]
so you gotta login first to your snapchat account in that browser then rerun it

**Comment by SmiluxByte** [comment]
working now. But its sending to like 5 people. Is that right? because i could just send to a 
shortcut including all users. and how much snapscore per hour?

**Comment by efenatuyo** [comment]
it is sending to every group you are in using shortcut
